In [1]:
import pandas as pd
df=pd.read_csv("student_risk_dataset.csv")

df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10050 entries, 0 to 10049
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Student_ID               10050 non-null  int64
 1   Class                    10050 non-null  int64
 2   Region                   10050 non-null  object
 3   Maths_Score              10050 non-null  int64
 4   Science_Score            10050 non-null  int64
 5   English_Score            10050 non-null  int64
 6   Overall_Percentage       10050 non-null  float64
 7   App_Login_Count          10050 non-null  int64
 8   Video_Completion_Rate    10050 non-null  int64
 9   Attendance_Percentage    9558 non-null   float64
 10  Homework_Completion (%)  9565 non-null   float64
 11  Test_Attempts_Per_Month  10050 non-null  int64
 12  Parent_Involvement       10050 non-null  object
 13  Extra_Support_Classes    10050 non-null  object
 14  Fee_Status               10050 non-null  object
 15  Payment_Type             10050 non-null  object
 16  Installment_Regularity   10050 non-null  object
 17  Risk_Level               10050 non-null  object
dtypes: float64(3), int64(8), object(7)
memory usage: 1.4+ MB

,Student_ID,Class,Maths_Score,Science_Score,English_Score,Overall_Percentage,App_Login_Count,Video_Completion_Rate,Attendance_Percentage,Homework_Completion (%),Test_Attempts_Per_Month
count,10050.000000,10050.000000,10050.000000,10050.000000,10050.000000,10050.000000,10050.000000,10050.000000,9558.000000,9565.000000,10050.000000
mean,6003.337114,7.991144,70.803881,70.294328,70.298010,70.465406,19.405274,67.601692,75.471438,67.418714,4.462090
std,2886.987352,1.423129,16.956661,17.166936,17.163977,16.987811,9.184091,21.466427,17.480038,21.873042,1.837136
min,1001.000000,6.000000,20.000000,15.000000,15.000000,16.666667,1.000000,10.000000,30.000000,-10.000000,1.000000
25%,3503.250000,7.000000,61.000000,60.000000,60.000000,60.666667,12.000000,55.000000,64.000000,55.000000,3.000000
50%,6006.500000,8.000000,73.000000,73.000000,73.000000,73.000000,20.000000,70.000000,76.000000,70.000000,5.000000
75%,8502.750000,9.000000,83.000000,83.000000,83.000000,83.000000,27.000000,85.000000,89.000000,84.000000,6.000000
max,11000.000000,10.000000,95.000000,99.000000,99.000000,97.666667,34.000000,99.000000,120.000000,99.000000,7.000000

In [3]:
df.isnull().sum()

Student_ID                   0
Class                        0
Region                       0
Maths_Score                  0
Science_Score                0
English_Score                0
Overall_Percentage           0
App_Login_Count              0
Video_Completion_Rate        0
Attendance_Percentage      492
Homework_Completion (%)    485
Test_Attempts_Per_Month      0
Parent_Involvement           0
Extra_Support_Classes        0
Fee_Status                   0
Payment_Type                 0
Installment_Regularity       0
Risk_Level                   0
dtype: int64

In [5]:
df['Attendance_Percentage'].fillna(df['Attendance_Percentage'].median(),inplace=True)

df['Homework_Completion (%)'].fillna(df['Homework_Completion (%)'].median(),inplace=True)

In [6]:
df.isnull().sum()

Student_ID                 0
Class                      0
Region                     0
Maths_Score                0
Science_Score              0
English_Score              0
Overall_Percentage         0
App_Login_Count            0
Video_Completion_Rate      0
Attendance_Percentage      0
Homework_Completion (%)    0
Test_Attempts_Per_Month    0
Parent_Involvement         0
Extra_Support_Classes      0
Fee_Status                 0
Payment_Type               0
Installment_Regularity     0
Risk_Level                 0
dtype: int64

In [7]:
df=df[(df["Attendance_Percentage"]>=0) & (df['Attendance_Percentage']<=100)]

In [8]:
df=df[(df["Homework_Completion (%)"]>=0) & (df['Homework_Completion (%)']<=100)]

In [9]:
score_cols=['Maths_Score','Science_Score','English_Score']

for col in score_cols:
    df=df[(df[col]>=0) & (df[col]<=100)]

In [10]:
df=df.drop_duplicates(subset='Student_ID')

In [11]:
df['Parent_Involvement']=df['Parent_Involvement'].str.strip().str.lower()

df["Parent_Involvement"]=df['Parent_Involvement'].replace({'yes':'Yes',
'y':'Yes',
'no':'No',
'n':'No'})

In [12]:
df['Region']=df['Region'].str.title()
df['Fee_Status']=df['Fee_Status'].str.title()
df['Payment_Type']=df['Payment_Type'].str.title()

In [14]:
df[(df['Overall_Percentage']>80) & (df['Attendance_Percentage']<40)]

Empty DataFrame
Columns: [Student_ID, Class, Region, Maths_Score, Science_Score, English_Score, Overall_Percentage, App_Login_Count, Video_Completion_Rate, Attendance_Percentage, Homework_Completion (%), Test_Attempts_Per_Month, Parent_Involvement, Extra_Support_Classes, Fee_Status, Payment_Type, Installment_Regularity, Risk_Level]
Index: []

In [17]:
def improved_risk(row):
    if row['Overall_Percentage']<40 or row['Attendance_Percentage']<50 or row['Fee_Status']=='Overdue':
        return 'High'
    elif row['Overall_Percentage']<60:
        return 'Medium'
    else:
        return 'Low'
df['Risk_Level']=df.apply(improved_risk,axis=1)

In [19]:
df.to_csv("cleaned_student_dataset.csv",index=False)